[package]
name = "jarp"
version = "0.1.0"
authors = ["MusiKid <musikid@outlook.com>"]
edition = "2018"

[dependencies]
pnet = "0.27.0"
ipnetwork = "0.20.0"
rayon = "1.6.1"
num_cpus = "1.15.0"
interfaces = "0.0.8"
